services:
  # 1. The Relational Database
  postgres:
    image: postgres:15-alpine
    container_name: sc_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sc_network

  # 2. The Cache Layer
  redis:
    image: redis:7-alpine
    container_name: sc_redis
    ports:
      - "6379:6379"
    networks:
      - sc_network

  # 3. The Core Backend (Java) - NEW
  core-service:
    build: ./core-service
    container_name: sc_core
    ports:
      - "8080:8080"
    environment:
      # Override localhost with service names
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - sc_network

  # 4. Ingestion Service (Go)
  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: sc_ingestion
    ports:
      - "8081:8081"
    environment:
      - INGESTION_PORT=8081
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_HOST=${PINECONE_INDEX_HOST}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    networks:
      - sc_network

  # 5. Agent Service (Python)
  agent-service:
    build: ./agent-service
    container_name: sc_agent
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_HOST=${PINECONE_INDEX_HOST}
      # Now it can find the core service by name
      - JAVA_SERVICE_URL=http://core-service:8080/api
    depends_on:
      - postgres
      - redis
      - core-service
    networks:
      - sc_network

volumes:
  postgres_data:

networks:
  sc_network:
    driver: bridge