services:
  # 1. The Relational Database
  postgres:
    image: postgres:15-alpine
    container_name: sc_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sc_network

  # 2. The Cache Layer
  redis:
    image: redis:7-alpine
    container_name: sc_redis
    ports:
      - "6379:6379"
    networks:
      - sc_network

  ingestion-service:
    platform: linux/amd64
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: sc_ingestion
    ports:
      - "8081:8081"
    environment:
      - INGESTION_PORT=8081
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_HOST=${PINECONE_INDEX_HOST}
    networks:
      - sc_network

volumes:
  postgres_data:

networks:
  sc_network:
    driver: bridge