spring:
  application:
    name: core-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/supply_chain_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate Config
  jpa:
    hibernate:
      ddl-auto: update # Creates tables automatically (Use 'validate' in production)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
